/**
 * Frontend constants — mirrors backend values, never imported from backend.
 */

export const SUPPORTED_LANGUAGES = [
  { value: "English",   label: "English",    native: "English",  flag: "🇺🇸" },
  { value: "Hindi",     label: "Hindi",      native: "हिंदी",     flag: "🇮🇳" },
  { value: "Marathi",   label: "Marathi",    native: "मराठी",     flag: "🇮🇳" },
  { value: "Tamil",     label: "Tamil",      native: "தமிழ்",     flag: "🇮🇳" },
  { value: "Telugu",    label: "Telugu",     native: "తెలుగు",    flag: "🇮🇳" },
  { value: "Kannada",   label: "Kannada",    native: "ಕನ್ನಡ",    flag: "🇮🇳" },
  { value: "Gujarati",  label: "Gujarati",   native: "ગુજરાતી",   flag: "🇮🇳" },
  { value: "Malayalam", label: "Malayalam",  native: "മലയാളം",   flag: "🇮🇳" },
];

export const RISK_CLASS_CONFIG = {
  Low: {
    label: "Low Risk",
    color: "#22C55E",
    bg: "rgba(34,197,94,0.12)",
    border: "rgba(34,197,94,0.3)",
    glow: "rgba(34,197,94,0.2)",
  },
  Moderate: {
    label: "Moderate Risk",
    color: "#F59E0B",
    bg: "rgba(245,158,11,0.12)",
    border: "rgba(245,158,11,0.3)",
    glow: "rgba(245,158,11,0.2)",
  },
  Medium: {
    label: "Medium Risk",
    color: "#F59E0B",
    bg: "rgba(245,158,11,0.12)",
    border: "rgba(245,158,11,0.3)",
    glow: "rgba(245,158,11,0.2)",
  },
  High: {
    label: "High Risk",
    color: "#EF4444",
    bg: "rgba(239,68,68,0.12)",
    border: "rgba(239,68,68,0.3)",
    glow: "rgba(239,68,68,0.2)",
  },
};

export const DECISION_STATUS_CONFIG = {
  Approved: {
    label: "Approved",
    color: "#22C55E",
    bg: "rgba(34,197,94,0.12)",
    border: "rgba(34,197,94,0.3)",
    icon: "CheckCircle",
  },
  Rejected: {
    label: "Rejected",
    color: "#EF4444",
    bg: "rgba(239,68,68,0.12)",
    border: "rgba(239,68,68,0.3)",
    icon: "XCircle",
  },
};

export const WORKFLOW_STEPS = [
  { id: 0, key: "gather",  label: "Gather",  icon: "ClipboardList", description: "Enter seller profile" },
  { id: 1, key: "score",   label: "Score",   icon: "Brain",         description: "ML risk scoring"      },
  { id: 2, key: "reason",  label: "Reason",  icon: "Sparkles",      description: "AI explanation"       },
  { id: 3, key: "decide",  label: "Decide",  icon: "Shield",        description: "Rules engine"         },
  { id: 4, key: "act",     label: "Act",     icon: "TrendingUp",    description: "Coaching plan"        },
];

export const SELLER_DATA_FIELDS = [
  {
    key: "sales_velocity_6m",
    label: "Sales Velocity (6 months)",
    unit: "₹",
    type: "number",
    min: 5000,
    max: 200000,
    step: 1000,
    placeholder: "102589",
    hint: "Total sales amount in last 6 months",
    group: "sales",
  },
  {
    key: "sales_growth_rate",
    label: "Sales Growth Rate",
    unit: "%",
    type: "number",
    min: -20,
    max: 40,
    step: 0.1,
    placeholder: "18.58",
    hint: "Month-over-month growth rate",
    group: "sales",
  },
  {
    key: "rto_rate",
    label: "RTO Rate",
    unit: "%",
    type: "number",
    min: 2,
    max: 25,
    step: 0.1,
    placeholder: "14.09",
    hint: "Return to origin rate (lower is better)",
    group: "delivery",
  },
  {
    key: "dispatch_sla_compliance",
    label: "Dispatch SLA Compliance",
    unit: "%",
    type: "number",
    min: 60,
    max: 100,
    step: 0.1,
    placeholder: "91.69",
    hint: "On-time dispatch percentage",
    group: "delivery",
  },
  {
    key: "avg_customer_rating",
    label: "Average Customer Rating",
    unit: "★",
    type: "number",
    min: 1,
    max: 5,
    step: 0.1,
    placeholder: "3.9",
    hint: "Average star rating from customers",
    group: "quality",
  },
  {
    key: "rating_trend",
    label: "Rating Trend",
    unit: "",
    type: "number",
    min: -0.5,
    max: 0.5,
    step: 0.001,
    placeholder: "0.091",
    hint: "Recent trend in ratings (positive = improving)",
    group: "quality",
  },
  {
    key: "order_cancellation_rate",
    label: "Order Cancellation Rate",
    unit: "%",
    type: "number",
    min: 0,
    max: 20,
    step: 0.1,
    placeholder: "7.03",
    hint: "Percentage of cancelled orders",
    group: "quality",
  },
  {
    key: "ad_spend_roi",
    label: "Ad Spend ROI",
    unit: "x",
    type: "number",
    min: 0.5,
    max: 5,
    step: 0.01,
    placeholder: "2.08",
    hint: "Return on advertising spend",
    group: "business",
  },
  {
    key: "account_age_months",
    label: "Account Age",
    unit: "months",
    type: "number",
    min: 1,
    max: 60,
    step: 1,
    placeholder: "55",
    hint: "Months since account creation",
    group: "business",
    isInt: true,
  },
  {
    key: "total_orders_6m",
    label: "Total Orders (6 months)",
    unit: "orders",
    type: "number",
    min: 50,
    max: 5000,
    step: 1,
    placeholder: "5000",
    hint: "Total orders fulfilled in last 6 months",
    group: "sales",
    isInt: true,
  },
  {
    key: "catalog_size",
    label: "Catalog Size",
    unit: "items",
    type: "number",
    min: 5,
    max: 500,
    step: 1,
    placeholder: "255",
    hint: "Number of active products listed",
    group: "business",
    isInt: true,
  },
  {
    key: "prior_loan_default",
    label: "Prior Loan Default",
    unit: "",
    type: "select",
    options: [
      { value: 0, label: "No — Clean record" },
      { value: 1, label: "Yes — Has defaulted" },
    ],
    placeholder: "Select",
    hint: "Any previous loan defaults on record",
    group: "credit",
  },
];

export const FIELD_GROUPS = [
  { key: "sales",    label: "Sales Performance",  icon: "TrendingUp"  },
  { key: "delivery", label: "Delivery Metrics",   icon: "Package"     },
  { key: "quality",  label: "Quality Signals",    icon: "Star"        },
  { key: "business", label: "Business Profile",   icon: "Building2"   },
  { key: "credit",   label: "Credit History",     icon: "CreditCard"  },
];

export const DEMO_PROFILES = [
  {
    label: "Strong Seller",
    description: "Low risk · High approval",
    color: "#22C55E",
    data: {
      seller_id: "DEMO_STRONG",
      language: "English",
      seller_data: {
        sales_velocity_6m: 150000, sales_growth_rate: 25, rto_rate: 5,
        dispatch_sla_compliance: 97, avg_customer_rating: 4.7, rating_trend: 0.2,
        order_cancellation_rate: 3, ad_spend_roi: 3.5, account_age_months: 48,
        total_orders_6m: 3500, catalog_size: 300, prior_loan_default: 0,
      },
    },
  },
  {
    label: "Borderline Seller",
    description: "Moderate risk · Under review",
    color: "#F59E0B",
    data: {
      seller_id: "DEMO_MED",
      language: "Hindi",
      seller_data: {
        sales_velocity_6m: 60000, sales_growth_rate: 5, rto_rate: 16,
        dispatch_sla_compliance: 80, avg_customer_rating: 3.5, rating_trend: -0.05,
        order_cancellation_rate: 10, ad_spend_roi: 1.5, account_age_months: 18,
        total_orders_6m: 800, catalog_size: 80, prior_loan_default: 0,
      },
    },
  },
  {
    label: "High Risk Seller",
    description: "High risk · Likely rejected",
    color: "#EF4444",
    data: {
      seller_id: "DEMO_HIGH",
      language: "Tamil",
      seller_data: {
        sales_velocity_6m: 15000, sales_growth_rate: -5, rto_rate: 23,
        dispatch_sla_compliance: 65, avg_customer_rating: 2.5, rating_trend: -0.3,
        order_cancellation_rate: 18, ad_spend_roi: 0.8, account_age_months: 4,
        total_orders_6m: 120, catalog_size: 12, prior_loan_default: 1,
      },
    },
  },
];
